- hosts: Master
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster.txt
      args:
        chdir: $HOME
        creates: cluster.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_setup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt
        
    
    - name: Run Kubernetes Manifest
  
      become: true
      tasks:
        - name: Clone Git Repository
          git:
            repo: https://github.com/sharonraju143/Project_final.git
            dest: /home/ubuntu/kubernetes
            force: yes
          become: false
          remote_user: ubuntu

        - name: Set permissions for the cloned directory
          file:
            path: /home/ubuntu/kubernetes
            state: directory
            owner: ubuntu
            group: ubuntu
            mode: "0755"

        - name: Set execute permission for deploy script
          file:
            path: /home/ubuntu/kubernetes/deploy.sh
            state: file
            owner: ubuntu
            group: ubuntu
            mode: "0755"

        - name: Execute deploy script
          command: /home/ubuntu/kubernetes/deploy.sh
          args:
            chdir: /home/ubuntu/kubernetes
          become: false
          remote_user: ubuntu    

