apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01
  labels:
    app: db01
spec:
  selector:
    matchLabels:
      app: db01
  replicas: 1
  template:
    metadata:
      labels:
        app: db01
    spec:
      containers:
      - name: db01
        image: manojsai5855/javanewdb
        ports:
        - name: db01-port
          containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "admin123"
